[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js handles routing internally, so we don't need catch-all redirects
# Only redirect specific static files if needed
[[redirects]]
  from = "/favicon.ico"
  to = "/assets/images/PrepVista_favicon.png"
  status = 301

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
