services:
  - type: web
    name: prepvista-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
